language: node_js
node_js:
- 6
- 8
matrix:
  fast_finish: true
notifications:
  email: false
  slack:
    secure: hcV0nADiIIpDuWezDehjC0RM4hOuyx5B2aiTFiMWhnz+NBR3naA6A1BPpXBk3jodTfg30FnopYaW38l2gcG+4O63q1aPBMAF1jFNEKDMKkNzwT9rOuEFLtWBZvQl7AHCBpfFnaX8KOZeUIMBLy1dnR+1fCcvxZ2wuEOw3cjiph1jG5UIqd/o/bWMIoN1Bhm/irYg+fWLbJNz3YWI66l6RpcNtEA+sWnAR+375ei1qIont0AEy/NNprujcFno7C2PAqT3KO3j0iNrUp4q3zZLo8NHLe0lrnVMtsZCq3y+xa/3w2lI0hm6RebcBEhe4lj45AeAzGEttDCuQmCth4WpDqwoRHBCS33P5WIie6CpL0QTWRQb1oMcYnjiabuhaaIsbZVgCZptsJCCtU7FSVIwcwIwL35HL51aP/DD6CXCTGDkksaebar77N1SLc7MirmpKrQUC5PDLo53WNr9WWUEMEzVoSYL6Gh7zoKLhH2QXKS34Dk5hMBJt3tuOyDjw10VCh4rAS9MjsAcVaV3yqPfl/qMEB1+53GID9IoNuVMwjuHXrj3SKYf4pjObWyf6WsyRBvh5Z3RiTK1ug4v834CB2trp6XIAKk3tZePhcftY66dicrIY4mOV/247m2p88dsUpg/wTvsAGdrVVNjiX+hTIeaAJcHPwBcco/IZ7wVIHY=
cache:
  directories:
  - "$HOME/.npm"
